service: lcchua-serverless-lambda-s3

provider:
  name: aws
  runtime: nodejs20.x
  stage: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

functions:
  processCSV:
    name: lcchua-processCSV
    handler: handler.processCSV
    events:
      - s3:
          bucket: lcchua-serverless-bucket-input
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    environment:
      FIXED_WIDTH_BUCKET: ${self:resources.Resources.fixedwidth.Properties.BucketName}
      NODE_ENV: production

resources:
  Resources:
    fixedwidth:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lcchua-serverless-bucket-output
